name: RealShop
main: fr.crafter.tickleman.RealShop.RealShopPlugin
version: 0.42
authors:
    - tickleman1
commands:
    mny:
        description: RealEconomy money commands
        usage: /<command> help
    rs:
        description: RealShop chest-shop commands
        usage: /<command> help
    rshop:
        description: RealShop chest-shop commands
        usage: /<command> help
