name: RealShop
main: fr.crafter.tickleman.RealShop.RealShopPlugin
version: 0.381
authors:
    - tickleman1
commands:
    mny:
        description: RealEconomy money commands
        usage: /<command> help
    shop:
        description: RealShop chest-shop commands
        usage: /<command> help
