name: RealShop
main: fr.crafter.tickleman.RealShop.RealShopPlugin
version: 0.371
authors:
  - tickleman1
commands:
  shop:
    description:RealShop chest-shop commands
    usage:/<command> help
